---
# PORT

server:
  port: 8080

---
# DB

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/salmal_db
    username: salmal
    password:
    driver-class-name: com.mysql.jdbc.Driver


---
# JPA

spring:
  jpa:
    hibernate:
      ddl-auto: create # 어느정도 엔티티 정해진 뒤에 validation & 마이그레이션 도입
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: false

  sql:
    init:
      mode: never