spring:
  config:
    activate:
      on-profile: local
    import: "classpath:BE-SECURITY/application-local.yml"

---

spring:
  config:
    activate:
      on-profile: dev
    import: "classpath:BE-SECURITY/application-dev.yml"

---

spring:
  config:
    activate:
      on-profile: prod
    import: "classpath:BE-SECURITY/application-prod.yml"